#!/usr/bin/env python3
"""
SIMPLE ARCHON-CHAT SYNC GENERATOR
Creates ready-to-use todo_write commands for chat synchronization

This tool generates the exact todo_write command needed to sync Archon tasks
with chat todos. Since the MCP API works perfectly in chat, this tool focuses
on generating the proper command format.

Usage:
    python3 scripts/simple_archon_sync.py > sync_command.txt
    
Then copy the generated command to chat and execute.

Author: DABS Automation System  
Created: 2025-08-23
"""

def generate_sync_command_template():
    """Generate template for manual Archon sync"""
    
    template = '''
# ARCHON-TO-CHAT TODO SYNCHRONIZATION COMMAND
# Generated by simple_archon_sync.py

# Step 1: Get tasks from Archon (execute this in chat)
mcp_archon_list_tasks(
    project_id="d010ff76-0202-48e4-8362-40c45e9de39a",
    include_closed=false,
    per_page=50
)

# Step 2: Transform and sync (execute this next)
# This command will be generated based on the task data from Step 1

# TRANSFORMATION RULES FOR MANUAL SYNC:
# 1. Map status: todo→pending, doing→in_progress, review→in_progress, done→completed
# 2. Add priority emoji: CRITICAL→🚨, HIGH→⚡, MEDIUM→📊, LOW→📝
# 3. Create content: "emoji title - brief_description (assignee)"
# 4. Use original Archon ID as todo ID for cross-reference

# TEMPLATE FOR TODO_WRITE COMMAND:
todo_write({
    "merge": false,
    "todos": [
        {
            "id": "archon-task-id",
            "content": "🚨 Task Title - Brief description (Assignee)",
            "status": "pending"
        },
        // ... repeat for each task
    ]
})
'''
    
    return template

def create_sync_function():
    """Create a function that can be copied into chat"""
    
    function_code = '''
# ARCHON SYNC FUNCTION - PASTE INTO CHAT
# This function can be used whenever you need to sync

async def sync_archon_todos():
    """One-command sync function for chat use"""
    
    # Get tasks from Archon
    tasks_result = await mcp_archon_list_tasks(
        project_id="d010ff76-0202-48e4-8362-40c45e9de39a",
        include_closed=False,
        per_page=50
    )
    
    # Transform to todos (manual transformation needed)
    todos = []
    for task in tasks_result["tasks"]:
        # Status mapping
        status_map = {
            "todo": "pending",
            "doing": "in_progress", 
            "review": "in_progress",
            "done": "completed"
        }
        
        # Priority emoji
        title = task["title"]
        if "CRITICAL" in title.upper():
            emoji = "🚨"
        elif "HIGH" in title.upper():
            emoji = "⚡"
        elif "MEDIUM" in title.upper():
            emoji = "📊"
        else:
            emoji = "📝"
        
        # Build content
        content = f"{emoji} {title}"
        if task.get("description"):
            brief_desc = task["description"][:80] + "..."
            content += f" - {brief_desc}"
        
        if task.get("assignee") and task["assignee"] != "User":
            content += f" ({task['assignee']})"
        
        todos.append({
            "id": task["id"],
            "content": content,
            "status": status_map.get(task["status"], "pending")
        })
    
    # Execute sync
    await todo_write({
        "merge": False,
        "todos": todos
    })
    
    return f"✅ Synced {len(todos)} tasks from Archon to chat todos"

# Usage: Just call sync_archon_todos() in chat
'''
    
    return function_code

def main():
    """Main function to generate sync tools"""
    
    print("=" * 80)
    print("ARCHON-TO-CHAT TODO SYNCHRONIZATION TOOLS")
    print("Generated:", "2025-08-23")
    print("=" * 80)
    print()
    
    print("## METHOD 1: STEP-BY-STEP MANUAL SYNC")
    print(generate_sync_command_template())
    print()
    
    print("=" * 80)
    print("## METHOD 2: ONE-COMMAND SYNC FUNCTION")
    print("Copy this entire function into chat, then call sync_archon_todos()")
    print("=" * 80)
    print(create_sync_function())
    print()
    
    print("=" * 80)
    print("## METHOD 3: QUICK SYNC (WHAT WE JUST DID)")
    print("This is exactly what was used to sync your tasks:")
    print("=" * 80)
    print("""
# 1. Get all tasks from Archon
result = mcp_archon_list_tasks(
    project_id="d010ff76-0202-48e4-8362-40c45e9de39a",
    include_closed=false,
    per_page=50
)

# 2. Transform and sync in one command  
todo_write({
    "merge": false,
    "todos": [
        // Transformed task data with:
        // - Original Archon ID as todo ID
        // - Priority emoji + title + brief description as content  
        // - Mapped status (todo→pending, doing→in_progress, etc.)
    ]
})
""")
    
    print()
    print("🎯 RECOMMENDATION:")
    print("Save this output to a file and use METHOD 3 for regular syncing.")
    print("The chat MCP tools work perfectly - no need for external API calls!")

if __name__ == "__main__":
    main()
